server:
  port: 23705

spring:
  application:
    name: app-monitor-fetcher
  boot:
    admin:
      client:
        url: http://localhost:9090

rocketmq:
  name-server: local-server1.com:9876
  producer:
    group: app-monitor-mq-producer-group
    send-message-timeout: 60000

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    owner: cocoawork
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 60000
    register: false
    subscribe: true
  consumer:
    retries: 0
    timeout: 60000



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

