server:
  port: 23705

spring:
  application:
    name: app-monitor-fetcher
  redis:
    host: local-server1.com
    port: 6379
    database: 0
    timeout: 6000


rocketmq:
  name-server: local-server1.com:9876;local-server2.com:9876
  producer:
    group: app-monitor-mq-producer-group
    send-message-timeout: 60000


dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    owner: cocoawork
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 60000
    register: false
    subscribe: true
    group: app-monitor
