server:
  port: 23705

spring:
  application:
    name: app-monitor-fetcher


  activemq:
    broker-url: tcp://baiduyun-server.com:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 10
      idle-timeout: 60

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    owner: cocoawork
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: zookeeper:localhost:2181
    timeout: 120000
    register: true
    subscribe: true
    group: app-monitor

activemq:
  topic: email-topic



