server:
  port: 23900

spring:
  application:
    name: app-mointor-web-api

seata:
  enabled: false
  tx-service-group: my_test_tx_group
  application-id: app-monitor-service
  config:
    type: file
    file:
      name: file.conf
  registry:
    type: file
    file:
      name: file.conf
  service:
    disable-global-transaction: false
