version: '3.3'
services:
  #mysql服务
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /usr/local/mysql/my.cnf:/etc/my.cnf   #挂载配置文件路径
      - /usr/local/mysql/data:/var/lib/mysql  #挂载数据路径
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'

  #redis服务
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
     - /usr/local/redis:/usr/local/etc/redis
    restart: on-failure

  #zookeeper注册中心
  zookeeper:
    image: zookeeper:3.5
    restart: on-failure
    ports:
      - 2181:2181


  #RocketMQ消息队列
  rocketmq-server:
    image: foxiswho/rocketmq:4.8.0
    restart: on-failure
    ports:
      - 9876:9876
    environment:
      JAVA_OPT_EXT: -Xms128M -Xmx128M -Xmn128m
    volumes:
      - /usr/local/rocketmq/store:/home/rocketmq/store
    command: sh mqnamesrv

  rockermq-broker:
    image: foxiswho/rocketmq:4.8.0
    restart: on-failure
    ports:
      - 10911:10911
      - 10912:10912
      - 10909:10909
    environment:
      NAMESRV_ADDR: rocketmq-server:9876
      JAVA_OPT_EXT: -Xms128M -Xmx128M -Xmn128m
    volumes:
      - /usr/local/rocketmq/store:/home/rocketmq/store
      - /usr/local/rocketmq/logs:/home/rocketmq/logs
      - /usr/local/rocketmq/conf:/home/rocketmq/conf
    command: sh mqbroker
    depends_on:
      - rocketmq-server

  #admin服务
  admin:
    restart: on-failure
    build:
      context: app-monitor-admin
    ports:
      - 9090:9090

  #service基础服务
  service:
    restart: on-failure
    build:
      context: app-monitor-service
    depends_on:
      - redis
      - db
      - rockermq-broker
      - zookeeper

  #web api
  web_api:
    restart: on-failure
    build:
      context: app-monitor-web-api
    ports:
      - 23900:23900
    depends_on:
      - service
      - zookeeper


  #数据抓取服务
  fetcher:
    restart: on-failure
    build:
      context: app-monitor-fetcher
    depends_on:
      - service
      - rockermq-broker
      - zookeeper


  #邮件中心
  email_center:
    restart: on-failure
    build:
      context: app-monitor-email-center
    depends_on:
      - rockermq-broker
