server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: app-store-rss

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      cocoawork:
        appstore:
          mapper: debug
  path: /
  file:
    max-history: 30


