spring:
  profiles:
    active: dev
  cache:
    type: redis
  datasource:
    initialization-mode: always

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #数据库主键自增
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: is_delete
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: reuse
    local-cache-scope: session
    cache-enabled: true
  mapper-locations: classpath:mapper/*Mapper.xml
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    redis:
      enabled: true
