server:
  port: 23700

spring:
  application:
    name: app-monitor-service

  #配置数据源
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/app_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    owner: cocoawork
  protocol:
    name: dubbo
    port: 20888
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
    timeout: 60000
    register: true
    group: app-monitor
    subscribe: false

rocketmq:
  name-server: local-server1.com:9876;local-server2.com:9876


