server:
  port: 23700

spring:
  application:
    name: app-monitor-service

  #配置数据源
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.220.207.117:3306/app_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      auto-commit: true
      maximum-pool-size: 100
      connection-timeout: 60000

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: 20801
  registry:
    protocol: zookeeper
    address: baiduyun-server.com:2181
    timeout: 120000
  provider:
    timeout: 60000
    retries: 0
    loadbalance: roundrobin
    actives: 200
  consumer:
    timeout: 6000
    retries: 0
    actives: 200