server:
  port: 23700

spring:
  application:
    name: app-monitor-service

  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/app_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 12345678
  boot:
    admin:
      client:
        url: http://admin:9090
  redis:
    host: redis
    port: 6379
    timeout: 60000
    database: 1

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: 20888
  registry:
    timeout: 60000
    register: true
    subscribe: false
    address: zookeeper://zookeeper:2181
  consumer:
    retries: 0
    timeout: 60000
  provider:
    retries: 0
    timeout: 60000

rocketmq:
  name-server: rocketmq-broker:9876


