server:
  port: 23900

spring:
  application:
    name: app-monitor-web-api
  boot:
    admin:
      client:
        url: http://localhost:9090
  mvc:
    hiddenmethod:
      filter:
        enabled: true     #支持解析_method隐藏域，用于前端发送PUT、DELETE请求
    contentnegotiation:
      favor-parameter: true  #基于参数format MediaType解析（仅限json、xml）
dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: zookeeper://localhost:2181
    timeout: 120000
    register: false
    subscribe: true
  consumer:
    timeout: 120000
    retries: 0
    check: false

swagger:
  enable: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always