server:
  port: 23900

spring:
  application:
    name: app-monitor-web-api
  boot:
    admin:
      client:
        url: http://localhost:9090

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: nacos://172.16.31.133:8848
    timeout: 120000
    register: false
    subscribe: true
  consumer:
    timeout: 120000
    retries: 0
    check: false

swagger:
  enable: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


