server:
  port: 23900

spring:
  application:
    name: app-monitor-web-api

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: 20888
  registry:
    address: zookeeper://localhost:2181
    timeout: 120000
    register: true
  consumer:
    timeout: 120000
    retries: 0
    check: false

swagger:
  enable: true
