#服务端口
server:
  port: 23800
spring:
  application:
    name: email-service

  mail:
    host: smtp.qq.com
    port: 25
    username: 657633723@qq.com
    password: qdryxgeumqqsbeib
    default-encoding: utf-8
    test-connection: true
  activemq:
    broker-url: tcp://34.92.164.47:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 10
      idle-timeout: 60
  jms:
    pub-sub-domain: true

activemq:
  topic: email-topic