#服务端口
server:
  port: 23800
spring:
  application:
    name: app-monitor-email-center

  mail:
    host: smtp.qq.com
    port: 25
    username: 657633723@qq.com
    password: qdryxgeumqqsbeib
    default-encoding: utf-8

rocketmq:
  name-server: local-server1.com:9876;local-server2.com:9876
