#服务端口
server:
  port: 23800
spring:
  application:
    name: app-monitor-email-center
  boot:
    admin:
      client:
        url: http://admin:9090

  mail:
    host: smtp.qq.com
    port: 25
    username: 657633723@qq.com
    password: qdryxgeumqqsbeib
    default-encoding: utf-8

rocketmq:
  name-server: rocketmq-broker:9876

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
