server:
  port: 23700

spring:
  application:
    name: app-monitor-service

  #配置数据源
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/app_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource



#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: none #数据库主键自增
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: 20801
  registry:
    protocol: zookeeper
    address: baiduyun-server.com:2181
    timeout: 120000
  provider:
    timeout: 60000
    retries: 0
  consumer:
    timeout: 6000
    retries: 0
    actives: 200

seata:
  enabled: false
  tx-service-group: my_test_tx_group
  application-id: app-monitor-service
  config:
    type: zk
    file:
      name: file.conf
    zk:
      server-addr: local-server1.com:2181

  registry:
    type: file
    file:
      name: file.conf
