server:
  port: 23700

spring:
  application:
    name: app-monitor-service

  #配置数据源
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.220.207.117:3306/app_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      maximum-pool-size: 100
      connection-timeout: 60000



#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: none #数据库主键自增
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml


dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: 20801
  registry:
    protocol: zookeeper
    address: baiduyun-server.com:2181
    timeout: 120000
  provider:
    timeout: 60000
    retries: 0
    loadbalance: roundrobin
    actives: 200
  consumer:
    timeout: 6000
    retries: 0
    actives: 200